"use client";

import { useState } from "react";
import { api } from "@/lib/client";
import type { GenerateResult } from "@/lib/dto";
import { Checkbox } from "@/components/forms";

function CopyButton({ text, label }: { text: string; label: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      className="btn-ghost text-xs"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setCopied(true);
          setTimeout(() => setCopied(false), 1500);
        } catch {
          /* clipboard may be unavailable */
        }
      }}
    >
      {copied ? "Copied ✓" : label}
    </button>
  );
}

export function PromptResultCard({ result }: { result: GenerateResult }) {
  return (
    <div className="space-y-4">
      {result.spoilerWarnings.length > 0 && (
        <div className="rounded-md border border-amber-700/50 bg-amber-950/30 p-3">
          <p className="text-xs font-semibold uppercase tracking-wide text-amber-300">
            Spoiler protection
          </p>
          <ul className="mt-1 list-disc pl-5 text-sm text-amber-200/90">
            {result.spoilerWarnings.map((w, i) => (
              <li key={i}>{w}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="card">
        <div className="mb-2 flex items-center justify-between">
          <h4 className="font-medium text-ember-400">Short prompt</h4>
          <CopyButton text={result.shortPrompt} label="Copy" />
        </div>
        <p className="whitespace-pre-wrap text-sm text-stone-200">{result.shortPrompt}</p>
      </div>

      <div className="card">
        <div className="mb-2 flex items-center justify-between">
          <h4 className="font-medium text-ember-400">Expanded prompt</h4>
          <CopyButton text={result.expandedPrompt} label="Copy" />
        </div>
        <p className="whitespace-pre-wrap text-sm text-stone-200">
          {result.expandedPrompt}
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        <div className="card">
          <h4 className="mb-2 font-medium text-stone-300">Negative prompt</h4>
          <p className="text-sm text-stone-400">{result.negativePrompt}</p>
        </div>
        <div className="card">
          <h4 className="mb-2 font-medium text-stone-300">Continuity notes</h4>
          {result.continuityNotes.length ? (
            <ul className="list-disc pl-5 text-sm text-stone-400">
              {result.continuityNotes.map((n, i) => (
                <li key={i}>{n}</li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-stone-500">None.</p>
          )}
        </div>
      </div>
      <p className="text-right text-xs text-stone-500">
        Generated by: <span className="text-stone-400">{result.source}</span>
      </p>
    </div>
  );
}

export default function GeneratePanel({
  campaignId,
  sceneId,
  aiAvailable,
  onSaved,
}: {
  campaignId: string;
  sceneId: string | null;
  aiAvailable: boolean;
  onSaved?: () => void;
}) {
  const [result, setResult] = useState<GenerateResult | null>(null);
  const [useAI, setUseAI] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [savedMsg, setSavedMsg] = useState<string | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    setSavedMsg(null);
    try {
      const res = await api.post<GenerateResult>(
        `/api/campaigns/${campaignId}/generate`,
        { sceneId: sceneId ?? undefined, ai: useAI }
      );
      setResult(res);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }

  async function savePrompt() {
    if (!result) return;
    await api.post(`/api/campaigns/${campaignId}/prompts`, {
      ...result,
      sceneId: result.sceneId ?? sceneId ?? undefined,
    });
    setSavedMsg("Saved to Visual Prompts.");
    onSaved?.();
  }

  async function saveCanonical() {
    if (!result) return;
    await api.post(`/api/campaigns/${campaignId}/references`, {
      sceneId: result.sceneId ?? sceneId ?? undefined,
      promptText: result.expandedPrompt,
      negativePrompt: result.negativePrompt,
      approvedByDm: true,
      notes: `Continuity: ${result.continuityNotes.join(" ")}`,
      generateImage: true,
    });
    setSavedMsg("Saved as a canonical visual reference.");
    onSaved?.();
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-3">
        <button className="btn-primary" onClick={generate} disabled={loading}>
          {loading ? "Generating…" : "Generate Scene Prompt"}
        </button>
        {aiAvailable && (
          <Checkbox label="Use AI" checked={useAI} onChange={setUseAI} />
        )}
        {!aiAvailable && (
          <span className="text-xs text-stone-500">
            AI off — using deterministic generator.
          </span>
        )}
      </div>

      {error && <p className="text-sm text-red-300">{error}</p>}

      {result && (
        <>
          <PromptResultCard result={result} />
          <div className="flex flex-wrap items-center gap-2">
            <button className="btn-secondary" onClick={savePrompt}>
              Save prompt
            </button>
            <button className="btn-primary" onClick={saveCanonical}>
              Save as Canonical
            </button>
            {savedMsg && <span className="text-sm text-emerald-400">{savedMsg}</span>}
          </div>
        </>
      )}
    </div>
  );
}
